create animals table
Kelvin-Ben/Vet-clinic-database pull request #1
Opened 2022-12-06 22:56 UTC by Kelvin-Ben

- I created a database schema and included a table called animals.
- I inserted the data required and I did some queries for the data as required.
- I have included screenshots of my work to show what I did in the query section.

![Screenshot_2022-12-07_01-04-53](https://user-images.githubusercontent.com/85459676/206041855-932dfc5e-2f07-49dc-bfa2-29172b640944.png)

![Screenshot_2022-12-07_01-16-52](https://user-images.githubusercontent.com/85459676/206041885-760c0e0f-9bf8-4633-a47e-08863da42cde.png)

![Screenshot_2022-12-07_01-20-46](https://user-images.githubusercontent.com/85459676/206041900-6601b139-c9c6-4434-86b7-4853bbc3e765.png)

![Screenshot_2022-12-07_01-23-50](https://user-images.githubusercontent.com/85459676/206041909-01782f31-11dc-4cc9-a93f-82ff59cf8318.png)

![Screenshot_2022-12-07_01-26-22](https://user-images.githubusercontent.com/85459676/206041918-bea6f6ef-2396-41e7-937e-8378f9968c46.png)

![Screenshot_2022-12-07_01-27-55](https://user-images.githubusercontent.com/85459676/206041928-ceb7b4e0-2d30-47aa-bf5b-a81b5465cc80.png)

![Screenshot_2022-12-07_01-29-20](https://user-images.githubusercontent.com/85459676/206041940-31141b76-3584-493f-94ed-d78a84547151.png)

![Screenshot_2022-12-07_01-34-56](https://user-images.githubusercontent.com/85459676/206041952-589def15-cb7d-46fe-821c-e1b165a0de5f.png)

2022-12-06 23:00 UTC, Munsa1 requested changes
Hi @Kelvin-Ben, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the new readme file [template](https://github.com/microverseinc/readme-template/blob/master/README.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-12-07 00:07 UTC, BenMukebo approved these changes
### Hi @Kelvin-Ben, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 


## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
### Hi @ , 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] It will be nice to add explicit steps to run your project locally, as this will be of help to non-technical users. This includes `npm install`, `npm start`, etc 🙃 

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.
- [OPTIONAL] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.. This includes `git clone URL` , `cd project_name`,  `npm install`, `npm start`, etc 🙃 

- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-07 00:07 UTC, BenMukebo commented on README.md
> +  <img src="murple_logo.png" alt="logo" width="140"  height="auto" />
- [OPTIONAL] The Nicroverse logo is broken, Please fix this 👍🏻

2022-12-07 00:07 UTC, BenMukebo commented on README.md
> +To get a local copy up and running, follow these steps.
- [OPTIONAL] It will be nice to add explicit steps to clone and test your project locally, as this will be of help to non-technical users.  🙃 

- please refer to this [template](https://github.com/microverseinc/readme-template), you can copy and paste the content but remember to customize it to your project.

2022-12-07 07:12 UTC, merged